# Generated by Django 4.2.11 on 2026-03-12 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Adeel Ur Rehman', max_length=200)),
                ('title', models.CharField(default='Backend Developer | Python Django Expert | API Specialist', max_length=300)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('bio', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
            },
        ),
    ]
